# Generated by Django 4.1.3 on 2022-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobs_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.ImageField(default='', upload_to='jobs'),
            preserve_default=False,
        ),
    ]
