# Generated by Django 4.1.3 on 2022-11-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_jobs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(upload_to='media/jobs'),
        ),
    ]
